# Generated by Django 3.0.7 on 2020-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bot_type', models.CharField(choices=[('Explicit Bot', 'Explicit Bot'), ('Promo Bot', 'Promo Bot'), ('Normal Comment', 'Normal Comment')], default='Normal Comment', max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
